name: docs

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps & build Sphinx
        run: |
          pip install numpy matplotlib sphinx sphinx-rtd-theme
          cd docs && make html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          # optional:
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true

